# Generated by Django 5.1.1 on 2024-09-29 19:36

from django.db import migrations

DEFAULT_TXN_CATEGORIES = [
    "GROCERIES",
    "EAT_OUT",
    "EMI",
    "TRANSPORT",
    "RENT",
    "HOUSE_UTILITIES",
    "BILLS",
    "SALARY"
]

def populate_txn_categories(app, schema_editor):
    txn_category_model = app.get_model("transactions", "TxnCategory")
    for txn_category in DEFAULT_TXN_CATEGORIES:
        category = txn_category_model(title=txn_category)
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_txn_categories)
    ]
